### ISSUE TITLE
FileSystem API를 이용한 이미지 관리

### ISSUE THREAD

**Issue by ghost** [szmc-team/SickZil-Machine#4]
[FileSystem API](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestFileSystem) 를 이용해 업로드된 이미지를 브라우저 내부 공간에 저장하려 합니다.

이로 인해 메모리에 모든 이미지를 올릴 필요 없이 자유로운 저장 / 불러오기가 가능해집니다.
현재 구현할 내용들은
- [ ] 이미지 다중 업로드 후 저장
- [ ] 저장한 이미지들의 불러오기
- [ ] 파일들의 자유로운 저장 / 삭제
(이 부분은 파일 관리자와 유사하게 구성이 가능해야 함 - JSON을 이용하여 가상 파일 구조로 해결해볼 예정)

**Comment by ghost** [comment]
디렉터리 구조를 담고 있는 JSON 파일을 생성 후 객체 안의 내용들로 파일 임시 저장 / 삭제 구현해볼 생각.

**Comment by ghost** [comment]
JSON에 기록되는 디렉터리 구조는 가상 디렉터리 구조이며, 실제 저장은 모두 한 곳에 이루어지게 할 수 밖에 없을 듯.

**Comment by ghost** [comment]
- 참고에 도움이 될 [자료](https://awayday.github.io/2017-11-05/anti-tree-table/)

**Comment by merongmerongmerong** [comment]
API가 비표준이고 핵심 기능이 obsolete 됐습니다
- https://developer.mozilla.org/en-US/docs/Web/API/File_and_Directory_Entries_API
- https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileEntry/createWriter

그래서 좀 더 브라우저 지원이 좋고 표준인 IndexedDB 기반으로 변경했습니다 #17 
- https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API
- https://github.com/localForage/localForage (적용 예정)
