### ISSUE TITLE
텐서 컬러 맵핑 함수

### ISSUE THREAD

**Issue by KUR-creative** [szmc-team/SickZil-Machine#9]
- [ ] Postprocess for result of snet(one-hot color scheme)
- [ ] Test mapping function (Use test framework) - it must be tested on (chrome) browser!

Reference: 
https://gitlab.com/szmc/nn-lab/-/blob/master/nnlab/data/image.py#L38
https://itnext.io/testing-your-javascript-in-a-browser-with-jest-puppeteer-express-and-webpack-c998a37ef887

**Comment by merongmerongmerong** [comment]
모델 전처리/후처리는 제가하는게 빠를것 같은데 
기대하는 인풋/아웃풋만 정해서 문서로 적어놓으면 만들어놓을게여 (one-hot <-> color 이런거)
